common:
  slack_hook: &slackHook
    put: slack
    params:
      attachments: |2
          [{
              "color": "danger",
              "actions": [
                    {
                      "type": "button",
                      "text": "View in Concourse",
                      "url": "https://ci.korifi.cf-app.com/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"
                    }
              ]
          }]
      channel: '#korifi-ci'
      text: |
        Pipeline *$BUILD_PIPELINE_NAME* failed :cry:

        Job is *$BUILD_JOB_NAME*
        Build name is *$BUILD_NAME*

  contour_logs: &contourLogs
    task: get-contour-logs
    file: korifi-ci/pipelines/tasks/get-contour-logs.yml
    image: ci-image
    params:
      CLUSTER_NAME: pr-e2e
      GCP_ZONE: europe-west1-b

groups:
- name: main
  jobs:
  - run-tests-main
  - run-e2es-main
  - publish-dev-images
- name: pr
  jobs:
  - allow-e2es
  - run-e2es-pr
- name: periodics
  jobs:
    - run-tests-periodic
    - run-e2es-periodic
- name: release
  jobs:
  - bump-major-version
  - bump-minor-version
  - publish-release

jobs:
# ===== main =====
- name: run-tests-main
  on_failure:
    do:
    - put: korifi-status
      params:
        path: korifi
        statuses:
        - state: failure
          context: "Concourse - tests (main)"
    - *slackHook
  plan:
  - in_parallel:
    - get: ci-image
    - get: golangci-lint-image
    - get: korifi
      trigger: true
    - get: korifi-ci

  - put: korifi-status
    params:
      path: korifi
      statuses:
        - state: pending
          context: "Concourse - tests (main)"

  - in_parallel:
      steps:
      - task: linter
        file: korifi-ci/pipelines/tasks/run-make-target.yml
        image: golangci-lint-image
        input_mapping:
          root: korifi
        params:
          TARGET: lint

      - in_parallel: &unit-integration
        - task: api-tests
          file: korifi-ci/pipelines/tasks/run-make-target.yml
          image: ci-image
          input_mapping:
            root: korifi
          output_mapping:
            coverage: coverage-api
          params:
            TARGET: test-api

        - task: controllers-tests
          file: korifi-ci/pipelines/tasks/run-make-target.yml
          image: ci-image
          input_mapping:
            root: korifi
          output_mapping:
            coverage: coverage-controllers
          params:
            TARGET: test-controllers

        - task: kpack-image-builder-tests
          file: korifi-ci/pipelines/tasks/run-make-target.yml
          image: ci-image
          input_mapping:
            root: korifi
          output_mapping:
            coverage: coverage-kib
          params:
            DIR: kpack-image-builder
            TARGET: test

        - task: statefulset-runner-tests
          file: korifi-ci/pipelines/tasks/run-make-target.yml
          image: ci-image
          input_mapping:
            root: korifi
          output_mapping:
            coverage: coverage-stset-runner
          params:
            DIR: statefulset-runner
            TARGET: test

  - task: publish-code-coverage
    image: ci-image
    file: korifi-ci/pipelines/tasks/publish-code-coverage.yml
    params:
      CC_TEST_REPORTER_ID: ((code-climate/test-reporter.id))

  - put: korifi-status
    params:
      path: korifi
      statuses:
        - state: success
          context: "Concourse - tests (main)"

- name: run-e2es-main
  on_failure:
    do:
    - put: korifi-status
      params:
        path: korifi
        statuses:
        - state: failure
          context: "Concourse - E2E (main)"
    - *slackHook
    - *contourLogs

  serial: true
  serial_groups:
  - pr-e2e
  plan:
  - in_parallel:
    - get: ci-image
    - get: korifi
      trigger: true
      passed:
        - run-tests-main
    - get: korifi-ci
    - get: gcloud-image
    - get: cf-k8s-secrets

  - put: korifi-status
    params:
      path: korifi
      statuses:
        - state: pending
          context: "Concourse - E2E (main)"

  - do: &end-to-ends
    - task: get-ip-addr
      file: korifi-ci/pipelines/tasks/get-terraform-property.yml
      image: gcloud-image
      params:
        CLUSTER_NAME: pr-e2e
        PROPERTY: pr_e2e_ip

    - task: install-korifi-dependencies
      file: korifi-ci/pipelines/tasks/install-korifi-dependencies.yml
      image: ci-image
      params:
        CLUSTER_NAME: pr-e2e
        GCP_ZONE: europe-west1-b

    - task: deploy-korifi
      privileged: true
      file: korifi-ci/pipelines/tasks/deploy-korifi.yml
      image: ci-image
      params:
        CLUSTER_NAME: pr-e2e
        GCP_ZONE: europe-west1-b

    - task: set-account-env-vars
      file: korifi-ci/pipelines/tasks/set-account-env-vars.yml
      image: ci-image
      params:
        CLUSTER_NAME: pr-e2e
        GCP_ZONE: europe-west1-b
        ROOT_NAMESPACE: cf

    - load_var: accounts_env_vars
      file: accounts/env_vars.yaml

    - in_parallel:
      - task: run-smoke-tests
        file: korifi-ci/pipelines/tasks/run-smoke-tests.yml
        image: ci-image
        params:
          CF_ADMIN_KEY: ((.:accounts_env_vars.CF_ADMIN_KEY))
          CF_ADMIN_CERT: ((.:accounts_env_vars.CF_ADMIN_CERT))
          SMOKE_TEST_USER: cf-admin
          SMOKE_TEST_APPS_DOMAIN: pr-e2e.korifi.cf-app.com
          SMOKE_TEST_APP_ROUTE_PROTOCOL: https
          SMOKE_TEST_API_ENDPOINT: https://cf.pr-e2e.korifi.cf-app.com
          SMOKE_TEST_SKIP_SSL: true

      - task: run-e2e-tests
        file: korifi-ci/pipelines/tasks/run-e2e-tests.yml
        image: ci-image
        params:
          ROOT_NAMESPACE: cf
          API_SERVER_ROOT: https://cf.pr-e2e.korifi.cf-app.com
          APP_FQDN: pr-e2e.korifi.cf-app.com
          E2E_USER_NAME: ((.:accounts_env_vars.E2E_USER_NAME))
          E2E_USER_PEM: ((.:accounts_env_vars.E2E_USER_PEM))
          E2E_SERVICE_ACCOUNT: ((.:accounts_env_vars.E2E_SERVICE_ACCOUNT))
          E2E_SERVICE_ACCOUNT_TOKEN: ((.:accounts_env_vars.E2E_SERVICE_ACCOUNT_TOKEN))
          CF_ADMIN_KEY: ((.:accounts_env_vars.CF_ADMIN_KEY))
          CF_ADMIN_CERT: ((.:accounts_env_vars.CF_ADMIN_CERT))
          FULL_LOG_ON_ERR: yes-please

  - put: korifi-status
    params:
      path: korifi
      statuses:
        - state: success
          context: "Concourse - E2E (main)"
  ensure: &clean-pr-e2e-env
    in_parallel:
    - task: clean-gcp-artifact-registry
      file: korifi-ci/pipelines/tasks/clean-gcp-artifact-registry.yml
      image: ci-image
    - task: undeploy-korifi
      file: korifi-ci/pipelines/tasks/undeploy-korifi.yml
      image: ci-image
      attempts: 10
      params:
        CLUSTER_NAME: pr-e2e
        GCP_ZONE: europe-west1-b

- name: publish-dev-images
  on_failure:
    do:
    - put: korifi-status
      params:
        path: korifi
        statuses:
        - state: failure
          context: "Concourse - publish images (main)"
    - *slackHook
  plan:
  - in_parallel:
    - get: ci-image
    - get: korifi
      trigger: true
      passed:
        - run-e2es-main
    - get: korifi-ci
    - get: korifi-release-version

  - put: korifi-status
    params:
      path: korifi
      statuses:
        - state: pending
          context: "Concourse - publish images (main)"

  - task: publish-dev-images
    file: korifi-ci/pipelines/tasks/publish-dev-images.yml
    image: ci-image
    params:
      CLUSTER_NAME: pr-e2e
      GCP_ZONE: europe-west1-b
      REGISTRY_HOSTNAME: index.docker.io
      REGISTRY_USER: ((release-pipeline/dockerhub-auth.username))
      REGISTRY_PASSWORD: ((release-pipeline/dockerhub-auth.password))

  - put: korifi-status
    params:
      path: korifi
      statuses:
        - state: success
          context: "Concourse - publish images (main)"




# ===== PR =====
- name: allow-e2es
  plan:
  - in_parallel:
    - get: ci-image
    - get: korifi-ci
    - get: pr-label
      trigger: true

  - task: allow-e2e
    file: korifi-ci/pipelines/tasks/allow-e2e.yml
    image: ci-image
    params:
      KORIFI_BOT_TOKEN: ((github/korifi-bot-token))
      KORIFI_BOT_NAME: korifi-bot

- name: run-e2es-pr
  on_failure:
    do:
    - put: korifi-pr
      params:
        path: korifi-pr
        base_context: "Concourse "
        context: " e2e-tests (pull_request)"
        status: failure
    - *slackHook
    - *contourLogs
  serial: true
  serial_groups:
  - pr-e2e
  plan:
  - in_parallel:
    - get: ci-image
    - get: gcloud-image
    - get: korifi-ci
    - get: korifi
      resource: korifi-pr
      trigger: true
      version: every
    - get: cf-k8s-secrets

  - put: korifi-pr
    params:
      path: korifi
      base_context: "Concourse "
      context: " e2e-tests (pull_request)"
      status: pending

  - do: *end-to-ends

  - put: korifi-pr
    params:
      path: korifi
      base_context: "Concourse "
      context: " e2e-tests (pull_request)"
      status: success

  ensure: *clean-pr-e2e-env

# ===== periodics =====
- name: run-tests-periodic
  on_failure:
    *slackHook
  plan:
  - in_parallel:
    - get: ci-image
    - get: golangci-lint-image
    - get: korifi
    - get: korifi-ci
    - get: workdays-periodic-timer
      trigger: true
    - get: weekend-periodic-timer
      trigger: true
  - in_parallel: *unit-integration

- name: run-e2es-periodic
  on_failure:
    do:
    - *slackHook
    - *contourLogs
  serial: true
  serial_groups:
  - pr-e2e
  plan:
  - in_parallel:
    - get: ci-image
    - get: gcloud-image
    - get: korifi-ci
    - get: korifi
    - get: cf-k8s-secrets
    - get: workdays-periodic-timer
      trigger: true
    - get: weekend-periodic-timer
      trigger: true
  - do: *end-to-ends
  ensure: *clean-pr-e2e-env

# ===== release =====
- name: bump-major-version
  plan:
  - get: korifi-release-version
    params:
      bump: major
  - put: korifi-release-version
    params:
      file: korifi-release-version/version
  on_failure: *slackHook

- name: bump-minor-version
  plan:
  - get: korifi-release-version
    params:
      bump: minor
    passed:
    - publish-release
    trigger: true
  - put: korifi-release-version
    params:
      file: korifi-release-version/version
  on_failure: *slackHook

- name: publish-release
  plan:
  - in_parallel:
      steps:
      - get: korifi-ci
      - get: korifi
        passed:
        - run-e2es-main
      - get: korifi-release-version
      - get: ci-image
  - task: create-release
    file: korifi-ci/pipelines/tasks/create-release.yml
    image: ci-image
    params:
      CLUSTER_NAME: pr-e2e
      GCP_ZONE: europe-west1-b
      REGISTRY_HOSTNAME: index.docker.io
      REGISTRY_USER: ((release-pipeline/dockerhub-auth.username))
      REGISTRY_PASSWORD: ((release-pipeline/dockerhub-auth.password))
  - put: korifi-github-release
    params:
      globs:
      - release-output/korifi*.tgz
      name: korifi-release-version/version
      tag: korifi-release-version/version
      tag_prefix: v
      commitish: korifi/.git/ref
  on_failure: *slackHook

resource_types:
- name: slack-notification
  type: registry-image
  source:
    username: ((docker.user))
    password: ((docker.pass))
    repository: cfcommunity/slack-notification-resource
    tag: latest

- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

- name: github-status
  type: docker-image
  source:
    repository: resource/github-status

resources:
- name: korifi-pr
  type: pull-request
  check_every: 1m
  source:
    repository: cloudfoundry/korifi
    access_token: ((github/korifi-bot-token))
    base_branch: main
    ignore_drafts: true
    labels: ["e2e-allowed"]
    required_review_approvals: 0

- name: pr-label
  type: pull-request
  check_every: 1m
  source:
    repository: cloudfoundry/korifi
    access_token: ((github/korifi-bot-token))
    base_branch: main
    ignore_drafts: true
    required_review_approvals: 0

- name: korifi-ci
  type: git
  icon: git
  source:
    uri: https://github.com/cloudfoundry/korifi-ci.git
    branch: main

- name: cf-k8s-secrets
  type: git
  icon: git
  source:
    uri: ((github/cf-k8s-secrets.uri))
    branch: main
    private_key: ((github/cf-k8s-secrets.private_key))

- name: slack
  type: slack-notification
  icon: slack
  source:
    url: ((slack-notification.uri))

- name: ci-image
  type: registry-image
  source:
    repository: europe-west1-docker.pkg.dev/cf-on-k8s-wg/ci/ci
    tag: latest
    username: _json_key
    password: ((gcp-artifact-registry-writer))

- name: gcloud-image
  type: registry-image
  source:
    repository: europe-west1-docker.pkg.dev/cf-on-k8s-wg/ci/gcloud
    tag: latest
    username: _json_key
    password: ((gcp-artifact-registry-writer))

- name: korifi
  type: git
  icon: git
  source:
    uri: https://github.com/cloudfoundry/korifi.git
    branch: main

- name: korifi-status
  type: github-status
  icon: checkbox-marked
  source:
    repo: cloudfoundry/korifi
    access_token: ((github/korifi-bot-token))

- name: golangci-lint-image
  type: registry-image
  source:
    repository: golangci/golangci-lint
    tag: latest
    username: ((docker.user))
    password: ((docker.pass))

- name: korifi-github-release
  type: github-release
  icon: egg-easter
  source:
    access_token: ((github/korifi.create_release_access_token))
    drafts: true
    owner: cloudfoundry
    repository: korifi

- name: korifi-release-version
  type: semver
  icon: counter
  source:
    branch: main
    driver: git
    file: korifi-release/version
    initial_version: 0.1.0
    private_key: ((github/cf-k8s-secrets.private_key))
    uri: ((github/cf-k8s-secrets.uri))

- name: workdays-periodic-timer
  type: time
  source:
    interval: 20m
    start: 03:00 AM
    stop: 08:00 AM
    location: Europe/London
    initial_version: true

- name: weekend-periodic-timer
  type: time
  source:
    days: [Saturday, Sunday]
    interval: 20m
    start: 09:00 AM
    stop: 11:59 PM
    location: Europe/London
    initial_version: true
