platform: linux

inputs:
- name: korifi-ci

params:
  GCP_SERVICE_ACCOUNT_JSON: ((gcp-artifact-registry-writer))
  KPACK_REPO_NAME: pr-e2e-images
  KPACK_REPO_LOCATION: europe-west1
  CI_REPO_NAME: ci
  CI_REPO_LOCATION: europe-west1
  PROJECT: cf-on-k8s-wg

run:
  path: korifi-ci/pipelines/scripts/clean-gcp-artifact-registry.sh
