platform: linux

caches:
- path: docker/overlay2
- path: docker/buildkit

inputs:
- name: korifi-version
- name: korifi-ci
- name: korifi

outputs:
- name: release-output

params:
  REGISTRY_SERVICE_ACCOUNT_JSON: ((gcp-artifact-registry-writer))
  GCP_SERVICE_ACCOUNT_JSON: ((gcp-serviceaccount))
  GCP_ZONE:
  CLUSTER_NAME:

run:
  path: korifi-ci/pipelines/scripts/create-release.sh
