platform: linux
image_resource:
  type: registry-image
  source:
    repository: europe-west1-docker.pkg.dev/cf-on-k8s-wg/ci/gcloud
    tag: latest
    username: _json_key
    password: ((gcp-artifact-registry-writer))
inputs:
- name: cf-k8s-ci
- name: cf-k8s-secrets
params:
  CLUSTER_NAME:
  GCP_SERVICE_ACCOUNT_JSON: ((gcp-serviceaccount))
  RELEASE_CHANNEL: REGULAR
  WORKER_COUNT: "3"
run:
  path: cf-k8s-ci/pipelines/scripts/create-cluster.sh
