platform: linux

caches:
- path: docker/overlay2
- path: docker/buildkit

inputs:
- name: korifi-test-release-version
- name: korifi-ci
- name: korifi

outputs:
- name: release-output

params:
  GCP_SERVICE_ACCOUNT_JSON: ((gcp-serviceaccount))
  GCP_ZONE:
  CLUSTER_NAME:
  REGISTRY_HOSTNAME:
  REGISTRY_USER:
  REGISTRY_PASSWORD:
run:
  path: korifi-ci/pipelines/scripts/create-release.sh
