platform: linux
inputs:
- name: korifi-ci
- name: cf-k8s-secrets
params:
  AWS_ACCESS_KEY_ID: ((aws/terraform.access-key-id))
  AWS_SECRET_ACCESS_KEY: ((aws/terraform.secret-access-key))
run:
  path: korifi-ci/pipelines/scripts/delete-disks-eks.sh
