platform: linux

caches:
- path: docker/overlay2
- path: docker/buildkit

inputs:
- name: korifi-ci
- name: korifi

outputs:
- name: kube

params:
  REGISTRY_SERVICE_ACCOUNT_JSON: ((gcp-artifact-registry-writer))
  GCP_SERVICE_ACCOUNT_JSON: ((gcp-serviceaccount))
  GCP_ZONE:
  CLUSTER_NAME:
  USE_LETSENCRYPT:

run:
  path: korifi-ci/pipelines/scripts/deploy-korifi.sh
