platform: linux

inputs:
- name: korifi-ci
- name: kube

params:
  REGISTRY_SERVICE_ACCOUNT_JSON: ((gcp-artifact-registry-writer))
  GCP_SERVICE_ACCOUNT_JSON: ((gcp-serviceaccount))
  GCP_ZONE:
  CLUSTER_NAME:
  USE_LETSENCRYPT:
  DOCKER_SERVER:
  DOCKER_USERNAME:
  DOCKER_PASSWORD:

run:
  path: korifi-ci/pipelines/scripts/deploy-latest-korifi-release.sh
