platform: linux

caches:
- path: docker/overlay2
- path: docker/buildkit

inputs:
- name: cf-k8s-ci
- name: cf-k8s-controllers-pr

outputs:
- name: kube

params:
  REGISTRY_SERVICE_ACCOUNT_JSON: ((gcp-artifact-registry-writer))
  GCP_SERVICE_ACCOUNT_JSON: ((gcp-serviceaccount))
  GCP_ZONE:
  CLUSTER_NAME:

run:
  path: cf-k8s-ci/pipelines/scripts/deploy-cf-k8s.sh
