platform: linux

inputs:
- name: korifi-ci
- name: korifi

outputs:
- name: kube

params:
  GCP_SERVICE_ACCOUNT_JSON: ((gcp-serviceaccount))
  GCP_ZONE:
  CLUSTER_NAME:
  USE_LETSENCRYPT:

run:
  path: korifi-ci/pipelines/scripts/deploy-korifi-sts-runner.sh
