platform: linux

inputs:
- name: cf-k8s-secrets
- name: korifi-ci
- name: korifi

outputs:
- name: kube

params:
  AWS_ACCESS_KEY_ID: ((aws/terraform.access-key-id))
  AWS_REGION:
  AWS_SECRET_ACCESS_KEY: ((aws/terraform.secret-access-key))
  CLUSTER_NAME:
  CLUSTER_TYPE:
  DEPLOY_LATEST_RELEASE:
  DOCKER_PASSWORD:
  DOCKER_SERVER:
  DOCKER_USERNAME:
  GCP_SERVICE_ACCOUNT_JSON: ((gcp-serviceaccount))
  GCP_ZONE:
  REGISTRY_SERVICE_ACCOUNT_JSON: ((gcp-artifact-registry-writer))
  USE_LETSENCRYPT:

run:
  path: korifi-ci/pipelines/scripts/deploy-korifi.sh
