platform: linux
inputs:
- name: korifi-ci
- name: cf-k8s-secrets
outputs:
- name: terraform-output
params:
  CLUSTER_NAME:
  GCP_SERVICE_ACCOUNT_JSON: ((gcp-serviceaccount))
  PROPERTY:
run:
  path: korifi-ci/pipelines/scripts/get-terraform-property.sh
