platform: linux
inputs:
- name: korifi-ci
- name: korifi
- name: cf-k8s-secrets
params:
  AWS_ACCESS_KEY_ID: ((aws/terraform.access-key-id))
  AWS_REGION:
  AWS_SECRET_ACCESS_KEY: ((aws/terraform.secret-access-key))
  CLUSTER_NAME:
  CLUSTER_TYPE:
  DNS_SERVICE_ACCOUNT_JSON: ((gcp/ci-dns-admin.key))
  GCP_PROJECT_ID:
  GCP_SERVICE_ACCOUNT_JSON: ((gcp-serviceaccount))
  GCP_ZONE:
  USE_LETSENCRYPT:
run:
  path: korifi-ci/pipelines/scripts/install-korifi-dependencies.sh
