platform: linux
inputs:
- name: korifi-ci
- name: korifi
- name: terraform-output
params:
  KPACK_TAG:
  DOCKER_SERVER:
  DOCKER_USERNAME:
  DOCKER_PASSWORD:
  GCP_PROJECT_ID:
  CLUSTER_NAME:
  GCP_ZONE:
  GCP_SERVICE_ACCOUNT_JSON: ((gcp-serviceaccount))
  USE_LETSENCRYPT:
  DNS_SERVICE_ACCOUNT_JSON: ((gcp/ci-dns-admin.key))
  USE_PATCHED_KPACK:
run:
  path: korifi-ci/pipelines/scripts/install-korifi-dependencies.sh
