platform: linux
inputs:
- name: korifi-ci
- name: korifi
- name: terraform-output
params:
  KPACK_TAG:
  DOCKER_SERVER:
  DOCKER_USERNAME:
  DOCKER_PASSWORD:
  CLUSTER_NAME:
  GCP_ZONE:
  GCP_SERVICE_ACCOUNT_JSON: ((gcp-serviceaccount))
  DEP_DIR:
run:
  path: korifi-ci/pipelines/scripts/install-korifi-dependencies.sh
