platform: linux

caches:
  - path: /root/.cache/go-build
  - path: /go/pkg/mod

inputs:
- name: korifi-ci
- name: korifi
- name: dorifi
- name: kube

params:
  API_SERVER_ROOT:
  APP_PATH:
  KUBECONFIG: kube/kube.config

run:
  path: korifi-ci/pipelines/scripts/push-app.sh
