platform: linux

inputs:
- name: korifi-ci
- name: dorifi
- name: kube

params:
  GCP_SERVICE_ACCOUNT_JSON: ((gcp-serviceaccount))
  CLUSTER_TYPE:
  CLUSTER_NAME:
  GCP_ZONE:
  API_SERVER_ROOT:
  KUBECONFIG: kube/kube.config

run:
  path: korifi-ci/pipelines/scripts/push-long-living-app.sh
