platform: linux

caches:
  - path: /root/.cache/go-build
  - path: /go/pkg/mod

inputs:
- name: korifi-ci
- name: korifi
- name: dorifi
- name: multi-process
- name: sample-broker
- name: kube

params:
  GCP_SERVICE_ACCOUNT_JSON: ((gcp-serviceaccount))
  CLUSTER_TYPE:
  CLUSTER_NAME:
  GCP_ZONE:
  AWS_REGION:
  API_SERVER_ROOT:
  APP_PATH:
  KUBECONFIG: kube/kube.config

run:
  path: korifi-ci/pipelines/scripts/push-app.sh
