platform: linux

caches:
  - path: /root/.cache/go-build
  - path: /go/pkg/mod

inputs:
- name: korifi-ci
- name: korifi
- name: dorifi

params:
  API_SERVER_ROOT:
  APP_FQDN:
  AWS_ACCESS_KEY_ID: ((aws/terraform.access-key-id))
  AWS_REGION:
  AWS_SECRET_ACCESS_KEY: ((aws/terraform.secret-access-key))
  CF_ADMIN_PEM:
  CF_ADMIN_TOKEN:
  CF_USER_TOKEN:
  CLUSTER_NAME:
  CLUSTER_TYPE:
  CLUSTER_VERSION_MAJOR:
  CLUSTER_VERSION_MINOR:
  E2E_LONGCERT_USER_NAME:
  E2E_LONGCERT_USER_PEM:
  E2E_SERVICE_ACCOUNT:
  E2E_SERVICE_ACCOUNT_TOKEN:
  E2E_UNPRIVILEGED_SERVICE_ACCOUNT:
  E2E_UNPRIVILEGED_SERVICE_ACCOUNT_TOKEN:
  E2E_USER_NAME:
  E2E_USER_PEM:
  E2E_USER_TOKEN:
  FULL_LOG_ON_ERR:
  GCP_SERVICE_ACCOUNT_JSON: ((gcp-serviceaccount))
  GCP_ZONE:
  GINKGO_NODES:
  GOOGLE_APPLICATION_CREDENTIALS:
  ROOT_NAMESPACE:
  DEFAULT_APP_BITS_PATH:
run:
  path: korifi-ci/pipelines/scripts/run-e2e-tests.sh
