platform: linux

caches:
  - path: /root/.cache/go-build
  - path: /go/pkg/mod

inputs:
- name: korifi-ci
- name: korifi
- name: cf-k8s-secrets

params:
  TERRAFORM_SERVICE_ACCOUNT_JSON: ((gcp-serviceaccount))
  AWS_ACCESS_KEY_ID: ((aws/terraform.access-key-id))
  AWS_REGION:
  AWS_SECRET_ACCESS_KEY: ((aws/terraform.secret-access-key))
  CLUSTER_NAME:
  CLUSTER_TYPE:
  GCP_SERVICE_ACCOUNT_JSON: ((gcp-serviceaccount))
  GCP_ZONE:
  API_SERVER_ROOT:
  ROOT_NAMESPACE: cf

run:
  path: korifi-ci/pipelines/scripts/run-crds-tests.sh
