platform: linux

caches:
  - path: ../../../root/.cache/go-build
  - path: ../../../go/pkg/mod

inputs:
- name: korifi-ci
- name: korifi
- name: kube

params:
  API_SERVER_ROOT:
  APP_FQDN:
  GINKGO_NODES:
  ROOT_NAMESPACE:
  KUBECONFIG: kube/kube.config
  FULL_LOG_ON_ERR:

run:
  path: korifi-ci/pipelines/scripts/run-e2e-tests.sh
