platform: linux

inputs:
- name: cf-k8s-ci
- name: cf-k8s-controllers-pr

outputs:
  - name: accounts

params:
  GCP_SERVICE_ACCOUNT_JSON: ((gcp-pr-e2e-k8s-admin))
  GCP_ZONE:
  CLUSTER_NAME:
  GINKGO_NODES:
  ROOT_NAMESPACE:

run:
  path: cf-k8s-ci/pipelines/scripts/set-account-env-vars.sh
