platform: linux

inputs:
- name: cf-k8s-secrets
- name: korifi-ci
- name: korifi

outputs:
  - name: accounts

params:
  AWS_ACCESS_KEY_ID: ((aws/terraform.access-key-id))
  AWS_REGION:
  AWS_SECRET_ACCESS_KEY: ((aws/terraform.secret-access-key))
  GCP_SERVICE_ACCOUNT_JSON: ((gcp-pr-e2e-k8s-admin))
  GCP_ZONE:
  CLUSTER_NAME:
  CLUSTER_TYPE:
  GINKGO_NODES:
  ROOT_NAMESPACE:

run:
  path: korifi-ci/pipelines/scripts/set-account-env-vars.sh
