platform: linux

inputs:
- name: cf-k8s-secrets
- name: korifi-ci
- name: korifi

outputs:
  - name: accounts

params:
  AWS_ACCESS_KEY_ID: ((aws/terraform.access-key-id))
  AWS_REGION:
  AWS_SECRET_ACCESS_KEY: ((aws/terraform.secret-access-key))
  CF_ADMIN_CERT:
  CF_ADMIN_KEY:
  CF_ADMIN_PEM:
  CF_ADMIN_TOKEN:
  CLUSTER_NAME:
  CLUSTER_TYPE:
  CLUSTER_VERSION_MAJOR:
  CLUSTER_VERSION_MINOR:
  E2E_LONGCERT_USER_NAME:
  E2E_LONGCERT_USER_PEM:
  E2E_SERVICE_ACCOUNT:
  E2E_SERVICE_ACCOUNT_TOKEN:
  E2E_USER_NAME:
  E2E_USER_PEM:
  E2E_USER_TOKEN:
  GCP_SERVICE_ACCOUNT_JSON: ((gcp-pr-e2e-k8s-admin))
  GCP_ZONE:
  GINKGO_NODES:
  ROOT_NAMESPACE:
  TERRAFORM_SERVICE_ACCOUNT_JSON: ((gcp-serviceaccount))

run:
  path: korifi-ci/pipelines/scripts/set-account-env-vars.sh
