platform: linux

inputs:
- name: korifi-ci

params:
  REGISTRY_SERVICE_ACCOUNT_JSON: ((gcp-artifact-registry-writer))
  GCP_SERVICE_ACCOUNT_JSON: ((gcp-serviceaccount))
  GCP_ZONE:
  CLUSTER_NAME:

run:
  path: korifi-ci/pipelines/scripts/undeploy-korifi.sh
