platform: linux

inputs:
- name: korifi-ci
- name: cf-k8s-secrets

params:
  AWS_ACCESS_KEY_ID: ((aws/terraform.access-key-id))
  AWS_REGION:
  AWS_SECRET_ACCESS_KEY: ((aws/terraform.secret-access-key))
  CLUSTER_NAME:
  CLUSTER_TYPE:
  GCP_SERVICE_ACCOUNT_JSON: ((gcp-serviceaccount))
  GCP_ZONE:
  REGISTRY_SERVICE_ACCOUNT_JSON: ((gcp-artifact-registry-writer))

run:
  path: korifi-ci/pipelines/scripts/undeploy-korifi.sh
