platform: linux

inputs:
- name: korifi-ci

params:
  AWS_REGION:
  CLUSTER_NAME:
  CLUSTER_TYPE:
  GCP_SERVICE_ACCOUNT_JSON: ((gcp-serviceaccount))
  GCP_ZONE:
  REGISTRY_SERVICE_ACCOUNT_JSON: ((gcp-artifact-registry-writer))

run:
  path: korifi-ci/pipelines/scripts/undeploy-korifi.sh
