common:
  on_failure: &slackHook
    do:
    - put: korifi-pr
      params:
        path: korifi-pr
        base_context: "Concourse "
        context: " e2e-tests (pull_request)"
        status: failure
    - put: slack
      params:
        attachments: |2
            [{
                "color": "danger",
                "actions": [
                      {
                        "type": "button",
                        "text": "View in Concourse",
                        "url": "https://ci.cf-k8s.cf/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME"
                      }
                ]
            }]
        channel: '#korifi-ci'
        text: |
          Pipeline *$BUILD_PIPELINE_NAME* failed :cry:

          Job is *$BUILD_JOB_NAME*
          Build name is *$BUILD_NAME*

groups:
- name: main
  jobs:
  - allow-e2es
  - run-e2es

jobs:
- name: allow-e2es
  plan:
  - in_parallel:
    - get: ci-image
    - get: korifi-ci
    - get: pr-label
      trigger: true

  - task: allow-e2e
    file: korifi-ci/pipelines/tasks/allow-e2e.yml
    image: ci-image
    params:
      KORIFI_BOT_TOKEN: ((github/pr-label-setter))

- name: run-e2es
  serial: true
  serial_groups:
  - pr-e2e
  plan:
  - in_parallel:
    - get: ci-image
    - get: gcloud-image
    - get: korifi-ci
    - get: korifi-pr
      trigger: true
    - get: cf-k8s-secrets
    - get: eirini-controller

  - put: korifi-pr
    params:
      path: korifi-pr
      base_context: "Concourse "
      context: " e2e-tests (pull_request)"
      status: pending

  - task: get-ip-addr
    file: korifi-ci/pipelines/tasks/get-terraform-property.yml
    image: gcloud-image
    params:
      CLUSTER_NAME: pr-e2e
      PROPERTY: pr_e2e_ip

  - task: install-korifi-dependencies
    input_mapping:
      korifi: korifi-pr
    file: korifi-ci/pipelines/tasks/install-korifi-dependencies.yml
    image: ci-image
    params:
      CLUSTER_NAME: pr-e2e
      GCP_ZONE: europe-west1-b

  - task: deploy-korifi
    privileged: true
    file: korifi-ci/pipelines/tasks/deploy-korifi.yml
    image: ci-image
    params:
      CLUSTER_NAME: pr-e2e
      GCP_ZONE: europe-west1-b

  - task: set-account-env-vars
    file: korifi-ci/pipelines/tasks/set-account-env-vars.yml
    image: ci-image
    params:
      CLUSTER_NAME: pr-e2e
      GCP_ZONE: europe-west1-b
      ROOT_NAMESPACE: cf

  - load_var: accounts_env_vars
    file: accounts/env_vars.yaml

  - task: run-e2e-tests
    file: korifi-ci/pipelines/tasks/run-e2e-tests.yml
    image: ci-image
    params:
      ROOT_NAMESPACE: cf
      API_SERVER_ROOT: https://cf.pr-e2e.cf-k8s.cf
      APP_FQDN: pr-e2e.cf-k8s.cf
      E2E_USER_NAMES: ((.:accounts_env_vars.E2E_USER_NAMES))
      E2E_USER_PEMS: ((.:accounts_env_vars.E2E_USER_PEMS))
      E2E_SERVICE_ACCOUNTS: ((.:accounts_env_vars.E2E_SERVICE_ACCOUNTS))
      E2E_SERVICE_ACCOUNT_TOKENS: ((.:accounts_env_vars.E2E_SERVICE_ACCOUNT_TOKENS))
      CF_ADMIN_KEY: ((.:accounts_env_vars.CF_ADMIN_KEY))
      CF_ADMIN_CERT: ((.:accounts_env_vars.CF_ADMIN_CERT))

  - put: korifi-pr
    params:
      path: korifi-pr
      base_context: "Concourse "
      context: " e2e-tests (pull_request)"
      status: success

  on_failure: *slackHook
  ensure:
    task: undeploy-korifi
    file: korifi-ci/pipelines/tasks/undeploy-korifi.yml
    image: ci-image
    attempts: 10
    params:
      CLUSTER_NAME: pr-e2e
      GCP_ZONE: europe-west1-b


resource_types:
- name: slack-notification
  type: registry-image
  source:
    username: ((docker.user))
    password: ((docker.pass))
    repository: cfcommunity/slack-notification-resource
    tag: latest

- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
- name: korifi-pr
  type: pull-request
  check_every: 1m
  source:
    repository: cloudfoundry/korifi
    access_token: ((github/pr-pipeline-token))
    base_branch: main
    ignore_drafts: true
    labels: ["e2e-allowed"]
    required_review_approvals: 0

- name: pr-label
  type: pull-request
  check_every: 1m
  source:
    repository: cloudfoundry/korifi
    access_token: ((github/pr-pipeline-token))
    base_branch: main
    ignore_drafts: true
    required_review_approvals: 0

- name: korifi-ci
  type: git
  icon: git
  source:
    uri: https://github.com/cloudfoundry/korifi-ci.git
    branch: main

- name: cf-k8s-secrets
  type: git
  icon: git
  source:
    uri: ((github/cf-k8s-secrets.uri))
    branch: main
    private_key: ((github/cf-k8s-secrets.private_key))

- name: eirini-controller
  type: git
  icon: git
  source:
    uri: https://github.com/cloudfoundry/eirini-controller.git
    branch: master

- name: slack
  type: slack-notification
  icon: slack
  source:
    url: ((slack-notification.uri))

- name: ci-image
  type: registry-image
  source:
    repository: europe-west1-docker.pkg.dev/cf-on-k8s-wg/ci/ci
    tag: latest
    username: _json_key
    password: ((gcp-artifact-registry-writer))

- name: gcloud-image
  type: registry-image
  source:
    repository: europe-west1-docker.pkg.dev/cf-on-k8s-wg/ci/gcloud
    tag: latest
    username: _json_key
    password: ((gcp-artifact-registry-writer))
