---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
sources:
- image: cloudfoundry/cf-k8s-api:latest
  path: .
  kubectlBuildkit:
    build:
      file: api/Dockerfile
destinations:
- image: cloudfoundry/cf-k8s-api:latest
  newImage: cloudfoundry/cf-on-k8s/korifi-api
